-- Create single string representation of PO data
CREATE OR REPLACE TABLE HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.PO_DATA_SINGLE_STRING AS 
SELECT 
    F_PURCHASING_ORDER.PURCHASING_DOCUMENT_ID,
    CONCAT(
        'Purchase Order ', F_PURCHASING_ORDER.PURCHASING_DOCUMENT_ID, 
        ' was created on ', F_PURCHASING_ORDER.PURCHASING_DOCUMENT_DATE, '.',
        ' The vendor is ', D_VENDOR.NAME, ' (', D_VENDOR.VENDOR_ID, ') from ', D_VENDOR.CITY, '.',
        ' The purchasing organization is ', D_PURCHASING_ORGANIZATION.DESCRIPTION, '.',
        ' The plant is ', D_PLANT.PLANT_NAME, '.',
        ' The material ordered is ', D_MATERIAL.MATERIAL_DESCRIPTION, ' (', D_MATERIAL.MATERIAL_NUMBER, ').',
        ' The order quantity is ', F_PURCHASING_ORDER.PURCHASE_ORDER_QUANTITY, ' ', D_MATERIAL.BASE_UOM_ID, '.',
        ' The order amount is ', F_PURCHASING_ORDER.PURCHASE_ORDER_AMOUNT, ' ', F_PURCHASING_ORDER.DOCUMENT_CURRENCY_ID, '.',
        ' The scheduled delivery date is ', F_PURCHASING_ORDER.SCHEDULED_DELIVERY_DATE, '.',
        ' The document type is ', D_PURCHASING_ORDER.PURCHASING_DOCUMENT_TYPE_TEXT, '.',
        ' The document status is ', D_PURCHASING_ORDER.PURCHASING_DOCUMENT_STATUS_TXT, '.',
        ' The payment terms are ', D_PURCHASING_ORDER.PAYMENT_TERMS
    ) AS po_information
FROM HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.F_PURCHASING_ORDER 
JOIN HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.D_PURCHASING_ORDER 
    ON F_PURCHASING_ORDER.PURCHASING_DOCUMENT_ID = D_PURCHASING_ORDER.PURCHASING_DOCUMENT_ID
JOIN HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.D_PURCHASING_ORGANIZATION 
    ON F_PURCHASING_ORDER.PURCHASING_ORGANIZATION_ID = D_PURCHASING_ORGANIZATION.PURCHASING_ORGANIZATION_ID
JOIN HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.D_VENDOR 
    ON F_PURCHASING_ORDER.VENDOR_ID = D_VENDOR.VENDOR_ID
JOIN HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.D_MATERIAL 
    ON F_PURCHASING_ORDER.MATERIAL_ID = D_MATERIAL.MATERIAL_ID
JOIN HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.D_PLANT 
    ON F_PURCHASING_ORDER.PLANT_ID = D_PLANT.PLANT_ID;

-- Create vector embeddings
CREATE OR REPLACE TABLE HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.PO_DATA_VECTORS AS 
SELECT 
    PURCHASING_DOCUMENT_ID,
    po_information,
    snowflake.cortex.EMBED_TEXT_1024('snowflake-arctic-embed-l-v2.0', po_information) as PO_EMBEDDINGS
FROM HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.PO_DATA_SINGLE_STRING;

-- Show the result of the transformations
SELECT *
FROM HOL_DATABASE.DHSAPPROD_DHSAPHANA_BI.PO_DATA_VECTORS
WHERE po_information LIKE '%Purchase Order%'
LIMIT 1;